name: Daily Fake News Upload

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 14:00 UTC (9 AM CST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  upload-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run upload script
        env:
          GITHUB_TOKEN: ${{ secrets.FAKE_NEWS_PAT }}
        run: python github_upload.py
